"""
Agent Protocol — Session Binding (HMAC-SHA256).

Provides cryptographic binding between a client and a session so that
knowing (or guessing) the session UUID alone is insufficient to hijack
the session.  During the handshake the client and server exchange nonces;
a shared secret is used to derive a *binding token* via HMAC-SHA256.
Every subsequent message carries a per-message HMAC proof in the
``Session-Binding`` header, proving the sender possesses the token.

Flow:
    1. Client generates ``client_nonce``, server generates ``server_nonce``.
    2. Both sides call ``derive_binding_token`` with the nonces, session id,
       and the pre-shared secret to obtain an identical ``binding_token``.
    3. Each message includes an HMAC of ``session_id + message_id`` keyed by
       the binding token (via ``create_message_binding``).
    4. The receiver calls ``verify_message_binding`` which uses
       ``hmac.compare_digest`` for constant-time comparison.

This module is PURE — only stdlib ``hmac`` / ``hashlib`` and pydantic.
"""

from __future__ import annotations

import hashlib
import hmac

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Model
# ---------------------------------------------------------------------------


class SessionBinding(BaseModel):
    """Captures the binding state negotiated during session handshake."""

    session_id: str = Field(
        description="Unique session identifier (UUID) this binding is tied to",
    )
    binding_token: str = Field(
        description="HMAC-SHA256 hex digest derived from both nonces and the shared secret",
    )
    client_nonce: str = Field(
        description="Random nonce generated by the client during handshake",
    )
    server_nonce: str = Field(
        description="Random nonce generated by the server during handshake",
    )

    model_config = {"extra": "ignore"}


# ---------------------------------------------------------------------------
# Token derivation
# ---------------------------------------------------------------------------


def derive_binding_token(
    client_nonce: str,
    server_nonce: str,
    session_id: str,
    shared_secret: str,
) -> str:
    """
    Derive the binding token from the handshake nonces and shared secret.

    Computes ``HMAC-SHA256(shared_secret, client_nonce + "\\x00" + server_nonce + "\\x00" + session_id)``
    and returns the hex digest.

    Args:
        client_nonce: Random nonce provided by the client.
        server_nonce: Random nonce provided by the server.
        session_id: The session identifier being bound.
        shared_secret: Pre-shared secret known to both parties.

    Returns:
        Hex-encoded HMAC-SHA256 digest used as the binding token.

    Raises:
        ValueError: If shared_secret is empty.
    """
    if not shared_secret:
        raise ValueError("shared_secret must not be empty")
    message = (client_nonce + "\x00" + server_nonce + "\x00" + session_id).encode("utf-8")
    return hmac.new(
        key=shared_secret.encode("utf-8"),
        msg=message,
        digestmod=hashlib.sha256,
    ).hexdigest()


# ---------------------------------------------------------------------------
# Per-message binding
# ---------------------------------------------------------------------------


def create_message_binding(
    session_id: str,
    message_id: str,
    binding_token: str,
) -> str:
    """
    Create the per-message HMAC proof for the ``Session-Binding`` header.

    Computes ``HMAC-SHA256(binding_token, session_id + "\\x00" + message_id)``
    and returns the hex digest.

    Args:
        session_id: Session identifier.
        message_id: Unique identifier for this message.
        binding_token: The binding token derived during handshake.

    Returns:
        Hex-encoded HMAC-SHA256 digest to attach as the binding proof.
    """
    message = (session_id + "\x00" + message_id).encode("utf-8")
    return hmac.new(
        key=binding_token.encode("utf-8"),
        msg=message,
        digestmod=hashlib.sha256,
    ).hexdigest()


def verify_message_binding(
    session_id: str,
    message_id: str,
    binding_token: str,
    provided_hmac: str,
) -> bool:
    """
    Verify a per-message binding proof using constant-time comparison.

    Recomputes the expected HMAC and compares it against *provided_hmac*
    via ``hmac.compare_digest`` to prevent timing side-channels.

    Args:
        session_id: Session identifier.
        message_id: Unique identifier for the message being verified.
        binding_token: The binding token derived during handshake.
        provided_hmac: The HMAC value supplied by the sender.

    Returns:
        True if the proof is valid, False if it was forged or tampered with.
    """
    expected = create_message_binding(session_id, message_id, binding_token)
    return hmac.compare_digest(expected, provided_hmac)
